#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------
#
# The following configuration files are used by these automated tests and must
# exist at the specified pathname:
#
# /var/ida/lib/constants.sh
# /var/ida/config/config.sh
#
#--------------------------------------------------------------------------------
# Load service constants and configuration settings

SCRIPT_ROOT=`dirname "$(realpath $0)"`

CONSTANTS_FILE="/var/ida/lib/constants.sh"

if [ -e $CONSTANTS_FILE ]
then
    . $CONSTANTS_FILE
else
    echo "The service constants file $CONSTANTS_FILE cannot be found. Aborting." >&2
    exit 1
fi

CONFIG_FILE="/var/ida/config/config.sh"

if [ -e $CONFIG_FILE ]
then
    . $CONFIG_FILE
else
    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
    exit 1
fi

VENV="/var/ida/venv"

if [ ! -d $VENV ]
then
    echo "The python environment $VENV cannot be found. Aborting." >&2
    exit 1
fi

if [ "$ROOT" = "" ]; then
    echo "The configuration variable $ROOT has not been defined Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------
# Verify that we are not in the production environment

if [ "$IDA_ENVIRONMENT" == "PRODUCTION" ]; then
    echo "This script can not be run in a production environment. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------
# Activate python environment

source $VENV/bin/activate

#--------------------------------------------------------------------------------
# Execute tests per the provided command line arguments

cd $SCRIPT_ROOT
cd ..

python -W ignore -m unittest discover -f -q tests.cli

if [ $? -ne 0 ]; then
    exit 1
fi

echo ""
echo "======================================"
echo "=== ALL EXECUTED TESTS SUCCESSFUL  ==="
echo "======================================"
echo ""

