#!/bin/bash

BRANCH="$1"

if [ "$BRANCH" == "" ]; then
    echo "Usage: $0 branch_name"
    exit 1
fi

if [ "$BRANCH" == "master" ]; then
    echo "Error: You may not delete the master branch!"
    exit 1
fi

if [ "$BRANCH" == "stable" ]; then
    echo "Error: You may not delete the stable branch!"
    exit 1
fi

git checkout master
git branch -D $1
git push private --delete $1
