#!/bin/bash
#
# C.f. https://24ways.org/2013/keeping-parts-of-your-codebase-private-on-github/
#
# Setup:
#
# git checkout master
# git remote add private <private repo URL>
# 
# E.g.
#
# git remote add private https://github.com/CSCfi/ida2-command-line-tools-dev.git
#
# To pull a private branch created on another machine:
#
# git fetch private
# git checkout <private branch name>
#
# The default branch in the private repo should be 'stable' and all pull requests
# should be made from feature branches in the private repo to the stable branch
# in the private repo, resulting in squash merges into stable. Then, when appropriate, 
# private/stable will be merged to origin/master.

SCRIPT=`basename $0`
BRANCH=$1

if [ "$BRANCH" = "" ]; then
    echo "Usage: $SCRIPT branch"
    exit 1
fi

STATUS=`git status 2>/dev/null | grep "On branch master"`

if [ "$STATUS" = "" ]; then
    echo "You must be in the master branch"
    exit 1
fi

git fetch
git pull

ORIGIN=`git config --get remote.origin.url`

if [ $? -ne 0 ]; then
    exit 1
fi

PRIVATE=`echo "$ORIGIN" | sed -e 's/\.git$/-dev.git/'`

if [ "$PRIVATE" = "-dev.git" ]; then
    echo "Unable to build private repo URL"
    exit 1
fi

git checkout -b $BRANCH

if [ $? -ne 0 ]; then
    exit 1
fi

git push -u private $BRANCH

if [ $? -ne 0 ]; then
    exit 1
fi

git status
