#!/usr/bin/env bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2022 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

SCRIPT_ROOT=`dirname "$(realpath $0)"`
TEST_ROOT=`dirname "$SCRIPT_ROOT"`

PYTHON="/opt/fairdata/python3/bin/python"

if [ ! -x "$PYTHON" ]; then
   PYTHON=`which python3`
fi

if [ ! -x "$PYTHON" ]; then
    echo "Could not find python3 executable" >&2
    exit 1
fi

cd $TEST_ROOT

rm -fr $TEST_ROOT/venv 2>/dev/null

$PYTHON -m venv $TEST_ROOT/venv

source $TEST_ROOT/venv/bin/activate

pip install --upgrade pip
pip install 'wheel>=0.34.2' --force-reinstall
pip install -r $TEST_ROOT/requirements.txt
