#!/usr/bin/env bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2022 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

# Only use the core os versions of commands

PATH="/usr/bin:/bin:/usr/sbin:/sbin"
export PATH

#--------------------------------------------------------------------------------

function portable_realpath() {
    if [[ "$OSTYPE" = "darwin"* ]]; then
        [[ $1 = /* ]] && echo "$1" || echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
    else
        realpath "$1"
    fi
}

SCRIPT_ROOT=`dirname "$(portable_realpath $0)"`
TEST_ROOT=`dirname "$SCRIPT_ROOT"`

cd $TEST_ROOT

if [ ! -d $TEST_ROOT/venv ]; then
    echo "The virtual environment does not exist!" >&2
    exit 1
fi

source $TEST_ROOT/venv/bin/activate

pip install --upgrade pip
pip install -r $TEST_ROOT/requirements.txt

